[2025-04-28T21:51:39.946+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hourly_forecast_dag.run_future_load_forecast manual__2025-04-28T21:51:38.434046+00:00 [queued]>
[2025-04-28T21:51:39.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hourly_forecast_dag.run_future_load_forecast manual__2025-04-28T21:51:38.434046+00:00 [queued]>
[2025-04-28T21:51:39.956+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-04-28T21:51:39.972+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_future_load_forecast> on 2025-04-28 21:51:38.434046+00:00
[2025-04-28T21:51:39.983+0000] {standard_task_runner.py:60} INFO - Started process 212 to run task
[2025-04-28T21:51:39.986+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'hourly_forecast_dag', 'run_future_load_forecast', 'manual__2025-04-28T21:51:38.434046+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/forecast_dag.py', '--cfg-path', '/tmp/tmp1z2cqmk7']
[2025-04-28T21:51:39.988+0000] {standard_task_runner.py:88} INFO - Job 78: Subtask run_future_load_forecast
[2025-04-28T21:51:40.041+0000] {task_command.py:423} INFO - Running <TaskInstance: hourly_forecast_dag.run_future_load_forecast manual__2025-04-28T21:51:38.434046+00:00 [running]> on host 58c0d1847783
[2025-04-28T21:51:40.133+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='hourly_forecast_dag' AIRFLOW_CTX_TASK_ID='run_future_load_forecast' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T21:51:38.434046+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T21:51:38.434046+00:00'
[2025-04-28T21:51:40.967+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/xgboost/core.py:158: UserWarning: [21:51:40] WARNING: /workspace/src/collective/../data/../common/error_msg.h:80: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  warnings.warn(smsg, UserWarning)

[2025-04-28T21:51:41.038+0000] {logging_mixin.py:188} INFO - âœ… Data upserted successfully!
[2025-04-28T21:51:41.042+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-28T21:51:41.053+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=hourly_forecast_dag, task_id=run_future_load_forecast, execution_date=20250428T215138, start_date=20250428T215139, end_date=20250428T215141
[2025-04-28T21:51:41.126+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-28T21:51:41.151+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
