[2025-04-28T09:56:34.142+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: update_energy_data_dag.run_update_energy_data scheduled__2025-04-24T12:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-04-28T09:56:34.159+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
[2025-04-28T09:56:34.186+0000] {taskinstance.py:1946} INFO - Dependencies not met for <TaskInstance: update_energy_data_dag.run_update_energy_data scheduled__2025-04-24T12:00:00+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2025-04-28T09:56:34.200+0000] {local_task_job_runner.py:160} INFO - Task is not able to be run
